# Generated by Django 2.1.5 on 2019-03-07 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlFromWebs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.URLField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('media_src', models.TextField(max_length=300)),
                ('media_titulo', models.TextField(max_length=300)),
                ('media_descripcion', models.TextField(max_length=300)),
            ],
        ),
    ]
