# Generated by Django 2.1.5 on 2019-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halcon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlfromwebs',
            name='media_host',
            field=models.TextField(default='', max_length=20),
        ),
    ]
