# Generated by Django 2.1.5 on 2019-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halcon', '0002_dlfromwebs_media_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlfromwebs',
            name='media_descripcion',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='dlfromwebs',
            name='media_src',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='dlfromwebs',
            name='media_titulo',
            field=models.TextField(default='', max_length=300),
        ),
    ]
