# Generated by Django 2.1.5 on 2019-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halcon', '0006_auto_20190408_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas_index', models.IntegerField()),
            ],
        ),
    ]
